### ISSUE TITLE
When logging in...

### ISSUE THREAD

**Issue by Virdari** [gameup-io/gameup-unity-sdk#18]
In your readme.md file, when logging in you have a private readonly SessionClient class variable. 

private readonly SessionClient sessionClient;

then, you use something like the following method to log in;

 public void onLoginClick()
    {
        // if you'd like to log the gamer in seamlessly...
        string deviceId = SystemInfo.deviceUniqueIdentifier;
        Client.LoginAnonymous (deviceId, (SessionClient session) => {
            Logger.d ("Logged in successfully");
            this.sessionClient = session;
        }, (status, reason) => {
            Logger.e ("Could not receive game information because " + reason + " with error code " + status);
        });

VS throws an error because you're trying to write to a readonly variable, and also this. part is unnecessary

**Comment by novabyte** [comment]
Hi @Virdari. Yes, you're right. The README is out of date. I'll update it as soon as I can.

We have a Unity guide in the documentation which walks through the entire SDK and our API:

https://heroiclabs.com/docs/guide/unity
