### ISSUE TITLE
Unable to Client.Ping from Unity Editor

### ISSUE THREAD

**Issue by Kinnear** [gameup-io/gameup-unity-sdk#46]
I've tried using the latest 0.2 version imported the dll as an asset into unity.
Added a Gameobject with a new script with a Client.Ping changed my developer key and am unable to get any feedback at all from any code inside Client.Ping();

Using Unity 5.3.5.

**Comment by novabyte** [comment]
@Kinnear Hmmm, can you paste an example of the exact code you've written in your Unity gameobject script? Make sure to remove the developer API key when you paste it here.

**Comment by novabyte** [comment]
@Kinnear Did you resolve the issue? Were you able to test the SDK?
