### ISSUE TITLE
Trying to create a MonoBehaviour using the 'new' keyword in sample program.

### ISSUE THREAD

**Issue by M2tM** [gameup-io/gameup-unity-sdk#6]
It appears to me (with not a *whole lot* of digging, so it may be a deeper issue) that SessionClient.cs is trying to new a WWWRequest which is itself some kind of singletonmonobehavior which is derived from Monobehaviour

I am getting tons of these warnings:

You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent().  Alternatively, your script can inherit from ScriptableObject or no base class at all
UnityEngine.MonoBehaviour:.ctor()
GameUp.SingletonMonoBehaviour`1:.ctor()
GameUp.WWWRequest:.ctor(MonoBehaviour, Uri, String, String, String)
GameUp.WWWRequest:.ctor(Uri, String, String, String)
GameUp.Client:Ping(SuccessCallback, ErrorCallback)
GameUp.Client:Ping(ErrorCallback)
GameUpTest:Start() (at Assets/GameUpTest.cs:31)

Without digging much further, I don't know if this warning is actually causing undesired behaviour, maybe you're somehow getting around the issue, but monobehaviours created with "new" typically don't function with coroutines as they aren't attached properly to game objects.

Even if this is not an issue, the warning spam is pretty messy. Attaching them to a gameObject would be preferrable. You may want to mark that gameobject with DontDestroyOnLoad as well: http://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

Any thoughts?

**Comment by novabyte** [comment]
@M2tM Hi, which version of Unity are you developing with?
This is something which has become a warning in Unity 5. We're working on an update at the moment.
Thanks for the report. :smiley:

**Comment by M2tM** [comment]
It's a warning in Unity 4.6 as well, not an error, but it is a warning precisely because monobehaviors rely on being in the scene graph to get certain update/coroutine/message broadcast behaviors. If you don't rely on any of this it's not an outright error, but it is something that should be/can be fixed quickly. :)

**Comment by M2tM** [comment]
I know about this precisely because I was doing the same thing as a C++ engineer learning Unity. I wanted to use coroutines on some objects, so made them monobehaviours, but the coroutines weren't working for me because they weren't attached to a game object.

**Comment by M2tM** [comment]
One last comment, you can't rely on constructors for monobehaviors, you'll need to move that to an initialize call, and then for convenience create a static factory method which creates/finds the desired parent game object, calls AddComponent, then calls initialize and returns that component.

**Comment by novabyte** [comment]
@M2tM I'm working on a patch right now. Would you be able to take a look at the PR and give me your feedback when it's ready?

**Comment by novabyte** [comment]
@M2tM This is fixed in commit 65a901c81334740d66793c4a76e03ab224cdcc7d and is now on master. Let me know if you have any more issues with the `WWWRequest` code.

**Comment by novabyte** [comment]
@M2tM I wanted to let you know I've just published a guide for this Unity SDK.
I hope it'll help you with your gamedev; let me know what you think of the guide and have any suggestions for improvements: https://gameup.io/docs/guide/unity/
